steps:
  # 0. Setup Artifact Bucket (Ensure it exists)
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args: ['-c', 'gsutil mb gs://$PROJECT_ID-build-artifacts || echo "Bucket likely exists"']

  # 1. Install Dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install', '--legacy-peer-deps']

  # 2. Prepare Web Assets (Create www folder & Download Libs for Offline)
  - name: 'ubuntu'
    args: 
      - 'bash'
      - '-c'
      - |
        mkdir -p www/libs www/fonts
        cp index.html www/
        cd www/libs
        apt-get update && apt-get install -y curl
        curl -L -o react.js https://unpkg.com/react@18/umd/react.production.min.js
        curl -L -o react-dom.js https://unpkg.com/react-dom@18/umd/react-dom.production.min.js
        curl -L -o babel.min.js https://unpkg.com/@babel/standalone/babel.min.js
        curl -L -o tailwindcss.js https://cdn.tailwindcss.com
        curl -L -o dexie.js https://unpkg.com/dexie@3.2.4/dist/dexie.min.js
        curl -L -o html5-qrcode.min.js https://unpkg.com/html5-qrcode
        curl -L -o jszip.min.js https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js
        cd ../fonts
        curl -L -o NotoSans-Regular.woff2 "https://fonts.gstatic.com/s/notosans/v36/o-0NIpQlx3QUlC5A4PNjhjRFSfiM7HBj.woff2"
        curl -L -o NotoSans-Bold.woff2 "https://fonts.gstatic.com/s/notosans/v36/o-0NIpQlx3QUlC5A4PNjFjFZSfiM7HBj.woff2"
        curl -L -o NotoSansMalayalam.woff2 "https://fonts.gstatic.com/s/notosansmalayalam/v26/sJoa3LYBihSvsoX-GE4nSS5_E7c4LZ_B0L1D4-o.woff2"
        curl -L -o NotoSansArabic.woff2 "https://fonts.gstatic.com/s/notosansarabic/v28/nwpCtLGrOAZMl5nJ_wfgRg3DrWFZWsnVBJ_sS6tlqHHFlj0EYJlsWk4yLBBN.woff2"
        curl -L -o NotoSansDevanagari.woff2 "https://fonts.gstatic.com/s/notosansdevanagari/v26/TuGoUUFzXI5FBtUq5a8bjKYTZjtRU6Sgv3NaV_SNmI0b6dEhvA.woff2"

  # 3. Add Android Platform (Generates android/ folder)
  - name: 'node:18'
    entrypoint: 'npx'
    args: ['cap', 'add', 'android']

  # 3.5 Inject Permissions & LargeHeap into AndroidManifest.xml
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i 's|<application|<uses-permission android:name="android.permission.CAMERA" />\n    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />\n    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />\n    <uses-permission android:name="android.permission.RECORD_AUDIO" />\n    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />\n    <uses-permission android:name="android.permission.INTERNET" />\n    <queries>\n        <intent>\n            <action android:name="android.speech.RecognitionService" />\n        </intent>\n    </queries>\n    <application android:largeHeap="true"|g' android/app/src/main/AndroidManifest.xml

  # 4. Sync Assets (Copies www to android/app/src/main/assets/public)
  - name: 'node:18'
    entrypoint: 'npx'
    args: ['cap', 'sync', 'android']

  # 5. Download existing keystore or skip (will create in build step)
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp gs://$PROJECT_ID-build-artifacts/shelflife-debug.keystore ./android/app/ 2>/dev/null || echo "No existing keystore, will create new one"

  # 6. Build APK with consistent signing
  - name: 'reactnativecommunity/react-native-android:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd android/app
        # Create keystore if it doesn't exist (keytool is available in Android container)
        if [ ! -f shelflife-debug.keystore ]; then
          echo "Creating new keystore..."
          keytool -genkeypair -v \
            -keystore shelflife-debug.keystore \
            -alias androiddebugkey \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass android -keypass android \
            -dname "CN=ShelfLife Debug, O=ShelfLife, C=US"
        else
          echo "Using existing keystore"
        fi
        cd ..
        chmod +x gradlew
        # Create signing config
        cat >> app/build.gradle << 'EOF'
        android {
            signingConfigs {
                debug {
                    storeFile file("shelflife-debug.keystore")
                    storePassword "android"
                    keyAlias "androiddebugkey"
                    keyPassword "android"
                }
            }
            buildTypes {
                debug {
                    signingConfig signingConfigs.debug
                }
            }
        }
        EOF
        ./gradlew assembleDebug

  # 7. Save keystore for future builds
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp ./android/app/shelflife-debug.keystore gs://$PROJECT_ID-build-artifacts/ 2>/dev/null || echo "Keystore upload skipped"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

artifacts:
  objects:
    location: 'gs://$PROJECT_ID-build-artifacts/'
    paths: ['android/app/build/outputs/apk/debug/app-debug.apk']
